export enum Permission {
  CREATE_USER = 'CREATE_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',
  READ_USER = 'READ_USER',
  CREATE_BOT = 'CREATE_BOT',
  READ_BOT = 'READ_BOT',
  UPDATE_BOT = 'UPDATE_BOT',
  DELETE_BOT = 'DELETE_BOT',
}
